syntax = "proto3";

option go_package = "OscarKV/pb";

message Checkpoint {
    string magic = 1;
    int32 walSegmentId = 2;
    uint64 createdAt = 3;
    repeated Levels levels = 4;
    repeated IngestBuffer buffer = 5; 
}

message Levels {
    repeated Table tables = 1;
}

message Table {
    uint64 id = 1; 
    bytes minKey = 2;
    bytes maxKey = 3;
    int32 size  = 4;
    int64 createdAt = 5;
    uint32 stale = 6;
}

message IngestBuffer {
    uint64 id = 1; 
    int32 level = 2;
    bytes minKey = 3;
    bytes maxKey = 4;
    int32 size  = 5;
    int64 createdAt = 6;
    uint32 stale = 7;
}
