// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pb/checkpoint.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Checkpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Magic         string                 `protobuf:"bytes,1,opt,name=magic,proto3" json:"magic,omitempty"`
	WalSegmentId  int32                  `protobuf:"varint,2,opt,name=walSegmentId,proto3" json:"walSegmentId,omitempty"`
	CreatedAt     uint64                 `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Levels        []*Levels              `protobuf:"bytes,4,rep,name=levels,proto3" json:"levels,omitempty"`
	Buffer        []*IngestBuffer        `protobuf:"bytes,5,rep,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_pb_checkpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_pb_checkpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_pb_checkpoint_proto_rawDescGZIP(), []int{0}
}

func (x *Checkpoint) GetMagic() string {
	if x != nil {
		return x.Magic
	}
	return ""
}

func (x *Checkpoint) GetWalSegmentId() int32 {
	if x != nil {
		return x.WalSegmentId
	}
	return 0
}

func (x *Checkpoint) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Checkpoint) GetLevels() []*Levels {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *Checkpoint) GetBuffer() []*IngestBuffer {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type Levels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*Table               `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Levels) Reset() {
	*x = Levels{}
	mi := &file_pb_checkpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Levels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Levels) ProtoMessage() {}

func (x *Levels) ProtoReflect() protoreflect.Message {
	mi := &file_pb_checkpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Levels.ProtoReflect.Descriptor instead.
func (*Levels) Descriptor() ([]byte, []int) {
	return file_pb_checkpoint_proto_rawDescGZIP(), []int{1}
}

func (x *Levels) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MinKey        []byte                 `protobuf:"bytes,2,opt,name=minKey,proto3" json:"minKey,omitempty"`
	MaxKey        []byte                 `protobuf:"bytes,3,opt,name=maxKey,proto3" json:"maxKey,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Stale         uint32                 `protobuf:"varint,6,opt,name=stale,proto3" json:"stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_pb_checkpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_pb_checkpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_pb_checkpoint_proto_rawDescGZIP(), []int{2}
}

func (x *Table) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Table) GetMinKey() []byte {
	if x != nil {
		return x.MinKey
	}
	return nil
}

func (x *Table) GetMaxKey() []byte {
	if x != nil {
		return x.MaxKey
	}
	return nil
}

func (x *Table) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Table) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Table) GetStale() uint32 {
	if x != nil {
		return x.Stale
	}
	return 0
}

type IngestBuffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	MinKey        []byte                 `protobuf:"bytes,3,opt,name=minKey,proto3" json:"minKey,omitempty"`
	MaxKey        []byte                 `protobuf:"bytes,4,opt,name=maxKey,proto3" json:"maxKey,omitempty"`
	Size          int32                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Stale         uint32                 `protobuf:"varint,7,opt,name=stale,proto3" json:"stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBuffer) Reset() {
	*x = IngestBuffer{}
	mi := &file_pb_checkpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBuffer) ProtoMessage() {}

func (x *IngestBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_pb_checkpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBuffer.ProtoReflect.Descriptor instead.
func (*IngestBuffer) Descriptor() ([]byte, []int) {
	return file_pb_checkpoint_proto_rawDescGZIP(), []int{3}
}

func (x *IngestBuffer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IngestBuffer) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *IngestBuffer) GetMinKey() []byte {
	if x != nil {
		return x.MinKey
	}
	return nil
}

func (x *IngestBuffer) GetMaxKey() []byte {
	if x != nil {
		return x.MaxKey
	}
	return nil
}

func (x *IngestBuffer) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *IngestBuffer) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *IngestBuffer) GetStale() uint32 {
	if x != nil {
		return x.Stale
	}
	return 0
}

var File_pb_checkpoint_proto protoreflect.FileDescriptor

const file_pb_checkpoint_proto_rawDesc = "" +
	"\n" +
	"\x13pb/checkpoint.proto\"\xac\x01\n" +
	"\n" +
	"Checkpoint\x12\x14\n" +
	"\x05magic\x18\x01 \x01(\tR\x05magic\x12\"\n" +
	"\fwalSegmentId\x18\x02 \x01(\x05R\fwalSegmentId\x12\x1c\n" +
	"\tcreatedAt\x18\x03 \x01(\x04R\tcreatedAt\x12\x1f\n" +
	"\x06levels\x18\x04 \x03(\v2\a.LevelsR\x06levels\x12%\n" +
	"\x06buffer\x18\x05 \x03(\v2\r.IngestBufferR\x06buffer\"(\n" +
	"\x06Levels\x12\x1e\n" +
	"\x06tables\x18\x01 \x03(\v2\x06.TableR\x06tables\"\x8f\x01\n" +
	"\x05Table\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06minKey\x18\x02 \x01(\fR\x06minKey\x12\x16\n" +
	"\x06maxKey\x18\x03 \x01(\fR\x06maxKey\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\x03R\tcreatedAt\x12\x14\n" +
	"\x05stale\x18\x06 \x01(\rR\x05stale\"\xac\x01\n" +
	"\fIngestBuffer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x16\n" +
	"\x06minKey\x18\x03 \x01(\fR\x06minKey\x12\x16\n" +
	"\x06maxKey\x18\x04 \x01(\fR\x06maxKey\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x05R\x04size\x12\x1c\n" +
	"\tcreatedAt\x18\x06 \x01(\x03R\tcreatedAt\x12\x14\n" +
	"\x05stale\x18\a \x01(\rR\x05staleB\fZ\n" +
	"OscarKV/pbb\x06proto3"

var (
	file_pb_checkpoint_proto_rawDescOnce sync.Once
	file_pb_checkpoint_proto_rawDescData []byte
)

func file_pb_checkpoint_proto_rawDescGZIP() []byte {
	file_pb_checkpoint_proto_rawDescOnce.Do(func() {
		file_pb_checkpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_checkpoint_proto_rawDesc), len(file_pb_checkpoint_proto_rawDesc)))
	})
	return file_pb_checkpoint_proto_rawDescData
}

var file_pb_checkpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_checkpoint_proto_goTypes = []any{
	(*Checkpoint)(nil),   // 0: Checkpoint
	(*Levels)(nil),       // 1: Levels
	(*Table)(nil),        // 2: Table
	(*IngestBuffer)(nil), // 3: IngestBuffer
}
var file_pb_checkpoint_proto_depIdxs = []int32{
	1, // 0: Checkpoint.levels:type_name -> Levels
	3, // 1: Checkpoint.buffer:type_name -> IngestBuffer
	2, // 2: Levels.tables:type_name -> Table
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_checkpoint_proto_init() }
func file_pb_checkpoint_proto_init() {
	if File_pb_checkpoint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_checkpoint_proto_rawDesc), len(file_pb_checkpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_checkpoint_proto_goTypes,
		DependencyIndexes: file_pb_checkpoint_proto_depIdxs,
		MessageInfos:      file_pb_checkpoint_proto_msgTypes,
	}.Build()
	File_pb_checkpoint_proto = out.File
	file_pb_checkpoint_proto_goTypes = nil
	file_pb_checkpoint_proto_depIdxs = nil
}
