// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pb/table.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TableIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        []*BlockOffset         `protobuf:"bytes,1,rep,name=offset,proto3" json:"offset,omitempty"`
	BloomFilter   []byte                 `protobuf:"bytes,2,opt,name=bloomFilter,proto3" json:"bloomFilter,omitempty"`
	MaxVersion    int64                  `protobuf:"varint,3,opt,name=maxVersion,proto3" json:"maxVersion,omitempty"`
	KeyCount      uint32                 `protobuf:"varint,4,opt,name=keyCount,proto3" json:"keyCount,omitempty"`
	StaleDataSize uint32                 `protobuf:"varint,5,opt,name=staleDataSize,proto3" json:"staleDataSize,omitempty"`
	ValueSize     uint32                 `protobuf:"varint,6,opt,name=valueSize,proto3" json:"valueSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableIndex) Reset() {
	*x = TableIndex{}
	mi := &file_pb_table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableIndex) ProtoMessage() {}

func (x *TableIndex) ProtoReflect() protoreflect.Message {
	mi := &file_pb_table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableIndex.ProtoReflect.Descriptor instead.
func (*TableIndex) Descriptor() ([]byte, []int) {
	return file_pb_table_proto_rawDescGZIP(), []int{0}
}

func (x *TableIndex) GetOffset() []*BlockOffset {
	if x != nil {
		return x.Offset
	}
	return nil
}

func (x *TableIndex) GetBloomFilter() []byte {
	if x != nil {
		return x.BloomFilter
	}
	return nil
}

func (x *TableIndex) GetMaxVersion() int64 {
	if x != nil {
		return x.MaxVersion
	}
	return 0
}

func (x *TableIndex) GetKeyCount() uint32 {
	if x != nil {
		return x.KeyCount
	}
	return 0
}

func (x *TableIndex) GetStaleDataSize() uint32 {
	if x != nil {
		return x.StaleDataSize
	}
	return 0
}

func (x *TableIndex) GetValueSize() uint32 {
	if x != nil {
		return x.ValueSize
	}
	return 0
}

type BlockOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinKey        []byte                 `protobuf:"bytes,1,opt,name=minKey,proto3" json:"minKey,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint32                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockOffset) Reset() {
	*x = BlockOffset{}
	mi := &file_pb_table_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockOffset) ProtoMessage() {}

func (x *BlockOffset) ProtoReflect() protoreflect.Message {
	mi := &file_pb_table_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockOffset.ProtoReflect.Descriptor instead.
func (*BlockOffset) Descriptor() ([]byte, []int) {
	return file_pb_table_proto_rawDescGZIP(), []int{1}
}

func (x *BlockOffset) GetMinKey() []byte {
	if x != nil {
		return x.MinKey
	}
	return nil
}

func (x *BlockOffset) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BlockOffset) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

var File_pb_table_proto protoreflect.FileDescriptor

const file_pb_table_proto_rawDesc = "" +
	"\n" +
	"\x0epb/table.proto\"\xd4\x01\n" +
	"\n" +
	"TableIndex\x12$\n" +
	"\x06offset\x18\x01 \x03(\v2\f.BlockOffsetR\x06offset\x12 \n" +
	"\vbloomFilter\x18\x02 \x01(\fR\vbloomFilter\x12\x1e\n" +
	"\n" +
	"maxVersion\x18\x03 \x01(\x03R\n" +
	"maxVersion\x12\x1a\n" +
	"\bkeyCount\x18\x04 \x01(\rR\bkeyCount\x12$\n" +
	"\rstaleDataSize\x18\x05 \x01(\rR\rstaleDataSize\x12\x1c\n" +
	"\tvalueSize\x18\x06 \x01(\rR\tvalueSize\"U\n" +
	"\vBlockOffset\x12\x16\n" +
	"\x06minKey\x18\x01 \x01(\fR\x06minKey\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\rR\x06lengthB\fZ\n" +
	"OscarKV/pbb\x06proto3"

var (
	file_pb_table_proto_rawDescOnce sync.Once
	file_pb_table_proto_rawDescData []byte
)

func file_pb_table_proto_rawDescGZIP() []byte {
	file_pb_table_proto_rawDescOnce.Do(func() {
		file_pb_table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_table_proto_rawDesc), len(file_pb_table_proto_rawDesc)))
	})
	return file_pb_table_proto_rawDescData
}

var file_pb_table_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_table_proto_goTypes = []any{
	(*TableIndex)(nil),  // 0: TableIndex
	(*BlockOffset)(nil), // 1: BlockOffset
}
var file_pb_table_proto_depIdxs = []int32{
	1, // 0: TableIndex.offset:type_name -> BlockOffset
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_table_proto_init() }
func file_pb_table_proto_init() {
	if File_pb_table_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_table_proto_rawDesc), len(file_pb_table_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_table_proto_goTypes,
		DependencyIndexes: file_pb_table_proto_depIdxs,
		MessageInfos:      file_pb_table_proto_msgTypes,
	}.Build()
	File_pb_table_proto = out.File
	file_pb_table_proto_goTypes = nil
	file_pb_table_proto_depIdxs = nil
}
